# Generated by Django 3.1.5 on 2021-01-23 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=15)),
                ('segundo_nombre', models.CharField(blank=True, max_length=15, null=True)),
                ('primer_apellido', models.CharField(max_length=15)),
                ('segundo_apellido', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=8)),
                ('nombre_colegio', models.CharField(max_length=30)),
                ('nombre_padre', models.CharField(max_length=60)),
                ('telefono_padre', models.CharField(max_length=8)),
                ('anyo_estudio', models.CharField(choices=[('quinto', 'Quinto Año de Bachillerato'), ('bachillerato', 'Bachiller Graduado')], max_length=12)),
                ('foto_carnet', models.FileField(upload_to='adjuntos/carnet')),
                ('copia_identidad', models.FileField(upload_to='adjuntos/identidad')),
                ('certificado', models.FileField(upload_to='adjuntos/certificado')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dias_clase', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('mp', 'Modalidad Presencial'), ('mo', 'Modalidad Online')], max_length=2)),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('siglas', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.estudiante')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.horario')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sede'),
        ),
    ]
