# Generated by Django 3.1.5 on 2021-01-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sede',
            old_name='signals',
            new_name='siglas',
        ),
    ]
