# Generated by Django 3.1.5 on 2021-01-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_matricula_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sede',
            name='siglas',
            field=models.CharField(max_length=8),
        ),
    ]
